# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GalaxySchema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SolarSystem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SolarSystem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSolarSystem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SolarSystem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SolarSystem
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SolarSystem
    def SpaceObjects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from GalaxySchema.SpaceObject import SpaceObject
            obj = SpaceObject()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SolarSystem
    def SpaceObjectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SolarSystem
    def SpaceObjectsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def SolarSystemStart(builder):
    builder.StartObject(2)

def Start(builder):
    SolarSystemStart(builder)

def SolarSystemAddId(builder, id):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder, id):
    SolarSystemAddId(builder, id)

def SolarSystemAddSpaceObjects(builder, spaceObjects):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spaceObjects), 0)

def AddSpaceObjects(builder, spaceObjects):
    SolarSystemAddSpaceObjects(builder, spaceObjects)

def SolarSystemStartSpaceObjectsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSpaceObjectsVector(builder, numElems: int) -> int:
    return SolarSystemStartSpaceObjectsVector(builder, numElems)

def SolarSystemEnd(builder):
    return builder.EndObject()

def End(builder):
    return SolarSystemEnd(builder)
