# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GalaxyMap

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Galaxy(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Galaxy()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGalaxy(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Galaxy
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Galaxy
    def SolarSystems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from GalaxyMap.SolarSystem import SolarSystem
            obj = SolarSystem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Galaxy
    def SolarSystemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Galaxy
    def SolarSystemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def GalaxyStart(builder):
    builder.StartObject(1)

def Start(builder):
    GalaxyStart(builder)

def GalaxyAddSolarSystems(builder, solarSystems):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(solarSystems), 0)

def AddSolarSystems(builder, solarSystems):
    GalaxyAddSolarSystems(builder, solarSystems)

def GalaxyStartSolarSystemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSolarSystemsVector(builder, numElems: int) -> int:
    return GalaxyStartSolarSystemsVector(builder, numElems)

def GalaxyEnd(builder):
    return builder.EndObject()

def End(builder):
    return GalaxyEnd(builder)
